<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\attachments\behaviors
 * @category   CategoryName
 */

namespace open20\amos\attachments\behaviors;

use open20\amos\admin\models\UserProfile;
use open20\amos\attachments\components\CustomUploadFile;
use open20\amos\attachments\FileModule;
use open20\amos\attachments\FileModuleTrait;
use open20\amos\attachments\interfaces\VirusScanInterface;
use open20\amos\attachments\models\AttachDatabankFile;
use open20\amos\attachments\models\AttachGalleryImage;
use open20\amos\attachments\models\AttachGenericFile;
use open20\amos\attachments\models\AttachGenericImage;
use open20\amos\attachments\models\File;
use open20\amos\core\views\toolbars\StatsToolbarPanels;
use open20\amos\core\utilities\ClassUtility;

use Imagine\Image\Box;
use Imagine\Image\Point;
use yii\imagine\Image;

use yii\base\Behavior;
use yii\base\ModelEvent;
use yii\db\ActiveRecord;
use yii\helpers\FileHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\validators\FileValidator;
use yii\web\UploadedFile;
use yii\helpers\Json;
use yii\base\InvalidArgumentException;

/**
 * Class FileBehavior
 * @property ActiveRecord $owner
 * @package file\behaviors
 */
class FileBehavior extends Behavior
{
    /**
     *
     */
    use FileModuleTrait;

    /**
     * @var array $permissions
     */
    public $permissions = [];

    public static $savedDatabankAttributes = [];

    /**
     * @var array $rules
     */
    var $rules = [];

    /**
     * @var array $fileValidators
     */
    private $fileValidators = [];

    /**
     * @var array $fileAttributes
     */
    private $fileAttributes = [];

    /**
     * @var array Attibutes to be overriden
     */
    private $overrideAttributes = [];

    /**
     * @var array $encryptedAttributes
     */
    public $encryptedAttributes = [];


    /**
     * Add files attributes as avaiable property for Getter
     * @return bool
     */
    public function canGetProperty($name, $checkVars = true)
    {
        $fileAttributes = self::getFileAttributes();

        if (in_array($name, $fileAttributes)) {
            return true;
        }

        return parent::canGetProperty($name, $checkVars);
    }

    /**
     * Add files attributes as avaiable property for Setter
     * @return bool
     */
    public function canSetProperty($name, $checkVars = true)
    {
        $fileAttributes = self::getFileAttributes();

        if (in_array($name, $fileAttributes)) {
            return true;
        }

        return parent::canSetProperty($name, $checkVars);
    }

    /**
     * Parse file behaviors and find for the choosed attribute for hasOne
     * or hasMultiple files relation
     * @param string $name
     * @return array|mixed
     * @throws \yii\base\UnknownPropertyException
     */
    public function __get($name)
    {
        /**
         * @var FileValidator $fileValidator
         */
        $fileValidator = $this->getFileValidator($name);

        if ($fileValidator) {
            if (isset($this->overrideAttributes[$name])) {
                return $this->overrideAttributes[$name];
            }

            if ($fileValidator->maxFiles == 1) {
                return $this->hasOneFile($name);
            } else {
                return $this->hasMultipleFiles($name);
            }
        }

        //No results? return the parent getter
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    /**
     * Setter is an override tool for validation
     */
    public function __set($name, $value)
    {
        $this->overrideAttributes[$name] = $value;

        return true;
    }

    /**
     * @inheritdoc
     */
    public function events()
    {
        $events = [
            ActiveRecord::EVENT_AFTER_DELETE => 'deleteUploads',
            ActiveRecord::EVENT_AFTER_INSERT => 'saveUploads',
            ActiveRecord::EVENT_AFTER_UPDATE => 'saveUploads',
            ActiveRecord::EVENT_BEFORE_VALIDATE => 'evalAttributes',
            ActiveRecord::EVENT_AFTER_VALIDATE => 'unevalAttributes'
        ];

        return $events;
    }


    /**
     * Iterate files and save by attribute
     * @param $event
     */
    public function saveUploads($event)
    {
        if (\Yii::$app->request->isConsoleRequest || !\Yii::$app->request->isPost) {
            return false;
        }
//        if(get_class($this->owner) == 'open20\amos\news\models\News') {
        $attributes = $this->getFileAttributes();
        if (!empty($attributes)) {
            foreach ($attributes as $attribute) {
                $this->saveAttributeUploads($attribute);
            }
        }
    }

    /**
     * Return array of attributes which may contain files
     * @return array
     */
    public function getFileAttributes()
    {
        $validators = $this->owner->getValidators();

        //Array of attributes
        $fileAttributes = [];

        //has file validator?
        $this->fileValidators = $this->getFileValidators($validators);

        foreach ($this->fileValidators as $fileValidator) {
            if (!empty($fileValidator)) {
                foreach ($fileValidator->attributes as $attribute) {
                    $fileAttributes[] = $attribute;
                }
            }
        }
        return $fileAttributes;
    }

    /**
     * @param $attributeName
     * @return bool|mixed|FileValidator|\yii\validators\Validator
     */
    public function getFileValidator($attributeName)
    {
        $fileValidators = $this->owner->getValidators();

        if (!empty($fileValidators)) {
            foreach ($fileValidators as $fileValidator) {
                /**
                 * @var FileValidator $fileValidator
                 */
                if (!empty($fileValidator) && $fileValidator instanceof FileValidator) {
                    foreach ($fileValidator->attributes as $attribute) {
                        if ($attribute == $attributeName) {
                            return $fileValidator;
                        }
                    }
                }
            }
        }
        return false;
    }

    /**
     * Check if owner model has file validator
     * @param ArrayObject|\yii\validators\Validator[]
     * @return \yii\validators\Validator[]
     */
    public function getFileValidators($validators)
    {
        $fileValidators = [];

        foreach ($validators as $validator) {
            /** @var \yii\validators\Validator $validator */
            $classname = $validator::className();

            if ($classname == 'yii\validators\FileValidator') {
                $fileValidators[] = $validator;
            }
        }

        return $fileValidators;
    }

    /**
     *
     * @param type $attribute
     * @return boolean
     */
    protected function saveAttributeUploads($attribute)
    {
        //Find shot model class name
        $ownerName = (new \ReflectionClass($this->owner))->getShortName();

        /**
         * @var UploadedFile[] $files
         */
        $files = UploadedFile::getInstancesByName($attribute)
            ?: UploadedFile::getInstancesByName("{$ownerName}[{$attribute}]");

        /**
         * BASE64 Encoded Files
         */
        $postData = \Yii::$app->request->post($ownerName);
        $fileAsString = (isset($postData[$attribute]) && !is_array($postData[$attribute]))
            ? $postData[$attribute]
            : null;

        if (!empty($fileAsString)) {
            $decodedFileTempName = hash('sha256', time() . $attribute);
            $decodedFilePath = sys_get_temp_dir() . '/' . $decodedFileTempName;

            //Decode
            file_put_contents($decodedFilePath, base64_decode($fileAsString));

            //Get File Type
            $mime = mime_content_type($decodedFilePath);
            $mimes = new \Mimey\MimeTypes;
            $extension = $mimes->getExtension($mime);

            //Create new file instance
            $newFile = new CustomUploadFile();
            $newFile->name = $decodedFileTempName . '.' . $extension;
            $newFile->tempName = $decodedFilePath;
            $newFile->type = $mime;

            $files[] = $newFile;
        }

        /**
         * @var FileValidator $fileValidator
         */
        $fileValidator = $this->getFileValidator($attribute);

        //Crop data
        $cropData = \Yii::$app->request->post("{$attribute}_data");

        //Upload file from gallery
        $csrfParam = \Yii::$app->request->csrfParam;
        $csrf = \Yii::$app->request->post($csrfParam);
        $datas = \Yii::$app->session->get($csrf);

        if (!empty($datas)) {
            $this->saveFileFromDatabanks($attribute, $csrf, $datas);
        }

        foreach ($files as $file) {
            if (
                $fileValidator
                && $fileValidator->maxFiles == 1
                && file_exists($file->tempName)
            ) {
                //Drop to make space for new image
                $this->deleteAttachments($this->owner, $attribute);
            }

            if ($cropData) {
                try {
                    $cropInfo = Json::decode($cropData);
                    // yii\base\InvalidArgumentException if there is any decoding error - so we catch the error
                } catch (InvalidArgumentException $iae) {
                    $cropInfo = array();
                }

                if (
                    (
                        isset($cropInfo['width'])
                        && ($cropInfo['width'] > 0)
                    )
                    && ((isset($cropInfo['height']))
                        && ($cropInfo['height'] > 0))
                ) {
                    $this->cropImage($file, $cropData);
                }
            }

            if (!$file->saveAs($this->getModule()->getUserDirPath($attribute) . $file->name)) {
                continue;
            }
        }

        if ($this->owner->isNewRecord) {
            return true;
        }

        $userTempDir = $this->getModule()->getUserDirPath($attribute);

        //If the directory doesn't exist go out
        if (!is_dir($userTempDir)) {
            return false;
        }

        foreach (FileHelper::findFiles($userTempDir) as $file) {
            $newFile = $this->getModule()->attachFile(
                $file,
                $this->owner,
                $attribute,
                true,
                false, (in_array($attribute, $this->encryptedAttributes)));
            if (!$newFile) {
                $this->owner->addError($attribute, 'File upload failed.');
                return true;
            } else {
                if(!in_array(get_class($this->owner), [UserProfile::className(), AttachGalleryImage::className(), AttachDatabankFile::className()])) {
//                    if($attribute == 'newsImage') {
//                    }
                    $source = \Yii::$app->request->post('uploadedFromSource');
                    $this->copyFileOnDatabanks($newFile, $cropInfo, $source);
                }
            }
        }
    }

    /**
     * @param $file File
     * @param $cropInfo
     * @return void
     * @throws \Exception
     */
    public function copyFileOnDatabanks($file, $cropInfo, $source)
    {
        if ($this->getModule()->autoSaveInDatabanks) {
            if (!empty($cropInfo)) {
                if(!in_array($source, ['upload_from_gallery', 'upload_from_shutterstock'])) {
                    $aspectRatio = round($cropInfo['width'] / $cropInfo['height'], 1);
                    $galleryImage = new AttachGalleryImage();
                    $galleryImage->gallery_id = 1;
                    $galleryImage->name = $file->name;
                    $galleryImage->aspect_ratio = $aspectRatio;
                    $galleryImage->save(false);
                    $newFile = $this->getModule()->attachFile($file->path, $galleryImage, 'attachImage', false, false, true, $file->name);
                    if ($newFile) {
                        $galleryImage->saveOnLuya();
                    }
                }
            } else {
                $databankFile = new AttachDatabankFile();
                $databankFile->name = $file->name;
                $databankFile->extension = $file->type;
                $databankFile->save(false);
                $newFile = $this->getModule()->attachFile($file->path, $databankFile, 'attachmentFile', false, false, true, $file->name);
                if ($newFile) {
                    $databankFile->saveOnLuya();
                }
            }

        }
    }

    /**
     * Drop all attachaments (Workaround for multiple attachaments on single file input)
     * @param ActiveRecord $model
     * @param $attribute
     * @return bool
     */
    private function deleteAttachments($model, $attribute)
    {
        return File::deleteAll([
            'model' => get_class($model),
            'attribute' => $attribute,
            'item_id' => $model->id
        ]);
    }

    /**
     *
     * @param UploadedFile $file
     * @param type $data
     */
    protected function cropImage(UploadedFile $file, $data)
    {
        //if temp file from post attributes is still present, the cropped image has to be saved
        if (file_exists($file->tempName)) {
            //The image file to be cropped
            $image = Image::getImagine()->open($file->tempName);

            // rendering information about crop of ONE option
            $cropInfo = Json::decode($data);

            if (isset($cropInfo['rotate'])) {
                $image->rotate($cropInfo['rotate']);
            }

            $cropInfo['x'] = abs($cropInfo['x']); //begin position of frame crop by X
            $cropInfo['y'] = abs($cropInfo['y']); //begin position of frame crop by Y
            $cropInfo['width'] = (int)$cropInfo['width']; //width of cropped image
            $cropInfo['height'] = (int)$cropInfo['height']; //height of cropped image

            //saving thumbnail
            $cropSizeThumb = new Box($cropInfo['width'], $cropInfo['height']); //frame size of crop
            $cropPointThumb = new Point($cropInfo['x'], $cropInfo['y']);
            $pathThumbImage = $file->tempName . '_thumb_' . $file->name;//$file->tempName;

            $image
                ->crop($cropPointThumb, $cropSizeThumb)
                ->save($pathThumbImage, ['quality' => 100]);

            @unlink($file->tempName);
            rename($pathThumbImage, $file->tempName);
        }
    }

    /**
     * When update save files before the validation
     * @param $event ModelEvent
     * @return bool|void
     */
    public function evalAttributes($event)
    {
        $attributes = $this->getFileAttributes();
        $sessImg = null;

        if (!(\Yii::$app instanceof \yii\console\Application) && \Yii::$app->request->isPost) {
            $csrfParam = \Yii::$app->request->csrfParam;
            $csrf = \Yii::$app->request->post($csrfParam);
            $sessImg = \Yii::$app->session->get($csrf);
        }

        if (!empty($attributes)) {
            foreach ($attributes as $attribute) {
                $files = UploadedFile::getInstancesByName(
                    ClassUtility::getClassBasename($this->owner->className()) . "[" . $attribute . "]"
                );

                //Let check if we need to scan the file
                $module = FileModule::getInstance();

                if ((is_object($module)) && ($module->enableVirusScan)) {
                    /**
                     * @var $scanner VirusScanInterface
                     */
                    $scanner = \Yii::createObject($module->virusScanClass);

                    foreach ($files as $file) {
                        $basePath = \Yii::getAlias('@common/uploads/temp');
                        $scanPath = realpath($basePath) . '/' . hash('md5', $file->tempName) . '.scan';
                        $scanReady = $file->saveAs($scanPath, false);
                        $scanResult = $scanner->scanFile($scanPath);

                        if ($scanReady && !$scanResult) {
                            unlink($file->tempName);

                            $this->owner->addError(
                                $attribute,
                                FileModule::t('amosattachments', 'The file {filename} is not safe and has been dropped', ['filename' => $file->name])
                            );
                        }

                        //Drop Copy Anyway
                        unlink($scanPath);
                    }
                }

                if (!empty($sessImg) && is_array($sessImg) && array_key_exists($attribute, $sessImg)) {
                    if (!empty($sessImg[$attribute]['id'])) {
                        $imgGallery = AttachGalleryImage::findOne($sessImg[$attribute]['id']);

                        if (!empty($imgGallery)) {
                            if (array_key_exists($attribute . '_data', \Yii::$app->request->post())) {
                                $newBody = [];

                                foreach (\Yii::$app->request->post() as $k => $post) {
                                    $newBody[$k] = $post;
                                }
                                //commentato perchè  a riga 316 si aspetta un json ed il json_decode si romperebbe, da capire a che serviva
                                // $newBody[$attribute.'_data'] = 'ok';
                                \Yii::$app->request->setBodyParams($newBody);
                            }
                        }
                    }
                }

                if (!empty($files)) {
                    $maxFiles = 1;

                    foreach ($this->fileValidators as $fileValidator) {
                        if (!empty($fileValidator)) {
                            if (in_array($attribute, $fileValidator->attributes)) {
                                $maxFiles = $fileValidator->maxFiles;
                            }
                        }
                    }

                    $setter = 'set' . ucfirst($attribute);

                    if (method_exists($this->owner, $setter)) {
                        $this->owner->{$setter}($maxFiles == 1 ? reset($files) : $files);
                    } else {
                        if ($maxFiles != 1) {
                            $this->owner->{$attribute} = [];

                            //List of files to be setted
                            $attributeFiles = [];

                            foreach ($files as $file) {
                                $attributeFiles[] = $file;
                            }

                            $this->owner->{$attribute} = $attributeFiles;
                        } else {
                            $this->owner->{$attribute} = reset($files);
                        }
                    }
                }
            }
        }
    }

    /**
     * Unset attributes from override
     * @return bool
     */
    public function unevalAttributes()
    {
        $attributes = $this->getFileAttributes();

        foreach ($attributes as $attribute) {
            //Drop Attribute Values, now let saveUploads do his job
            unset($this->owner->{$attribute});

            //Ensure var is unsetted from override
            if (isset($this->overrideAttributes[$attribute])) {
                unset($this->overrideAttributes[$attribute]);
            }
        }

        return true;
    }

    /**
     * @param $event
     */
    public function deleteUploads($event)
    {
        $files = $this->getFiles();

        foreach ($files as $file) {
            $this->getModule()->detachFile($file->id);
        }
    }

    /**
     * @param string $andWhere
     * @return File[]
     */
    public function getFiles($andWhere = '')
    {
        return $this->getFilesQuery()->all();
    }

    /**
     * @param string $andWhere
     * @return \yii\db\ActiveQuery
     */
    public function getFilesQuery($andWhere = '')
    {
        $fileQuery = File::find()
            ->where(
                [
                    'item_id' => $this->owner->getAttribute('id'),
                    'model' => $this->getModule()->getClass($this->owner)
                ]
            );
        $fileQuery->orderBy('is_main DESC, sort DESC');

        if ($andWhere) {
            $fileQuery->andWhere($andWhere);
        }

        return $fileQuery;
    }

    /**
     * DEPRECATED
     */
    public function getSingleFileByAttributeName($attribute = 'file', $sort = 'id')
    {
        $query = $this->getFilesByAttributeName($attribute, $sort);

        //Single result mode
        $query->multiple = false;

        return $this->hasOneFile($attribute, $sort);
    }

    /**
     * DEPRECATED
     */
    public function getFilesByAttributeName($attribute = 'file', $sort = 'id')
    {
        return $this->hasMultipleFiles($attribute, $sort);
    }

    /**
     * @param string $attribute
     * @param string $sort
     * @return \yii\db\ActiveQuery
     */
    public function hasMultipleFiles($attribute = 'file', $sort = 'id')
    {
        $fileQuery = File::find()
            ->where([
                'item_id' => $this->owner->id,
                'model' => $this->getModule()->getClass($this->owner),
                'attribute' => $attribute,
            ]);

        $fileQuery->orderBy([$sort => SORT_ASC]);

        //Single result mode
        $fileQuery->multiple = true;

        return $fileQuery;
    }

    /**
     * @param string $attribute
     * @param string $sort
     * @return \yii\db\ActiveQuery
     */
    public function hasOneFile($attribute = 'file', $sort = 'id')
    {
        $query = $this->hasMultipleFiles($attribute, $sort);

        //Single result mode
        $query->multiple = false;

        return $query;
    }

    /**
     * @param string $attribute
     * @return array
     */
    public function getInitialPreviewByAttributeName($attribute = 'file', $size = null)
    {
        $initialPreview = [];
        $userTempDir = $this->getModule()->getUserDirPath($attribute);

        if (is_dir($userTempDir)) {
            foreach (FileHelper::findFiles($userTempDir) as $file) {

                if (substr(FileHelper::getMimeType($file), 0, 5) === 'image') {
                    $initialPreview[] = Html::img(
                        [
                            '/'
                            . FileModule::getModuleName()
                            . '/file/download-temp',
                            'filename' => basename($file)
                        ],
                        ['class' => 'file-preview-image']
                    );
                } else {
                    $initialPreview[] = Html::beginTag('div', ['class' => 'file-preview-other'])
                        . Html::beginTag('span', ['class' => 'file-other-icon'])
                        . Html::tag('i', '', ['class' => 'glyphicon glyphicon-file'])
                        . Html::endTag('span')
                        . Html::endTag('div');
                }
            }
        }

        $files = $this->getFilesByAttributeName($attribute)->all();

        if (is_array($files)) {
            foreach ($files as $file) {
                /** @var File $file */

                if (substr($file->mime, 0, 5) === 'image') {
                    $initialPreview[] = Html::img($file->getUrl($size), ['class' => 'file-preview-image']);
                } else {
                    $initialPreview[] = Html::beginTag('div', ['class' => 'file-preview-other'])
                        . Html::beginTag('span', ['class' => 'file-other-icon'])
                        . Html::tag('i', '', ['class' => 'glyphicon glyphicon-file'])
                        . Html::endTag('span')
                        . Html::endTag('div');
                }
            }
            return $initialPreview;
        }

        return [];
    }

    /**
     * @param string $attribute
     * @return array
     */
    public function getInitialPreviewConfigByAttributeName($attribute = 'file')
    {
        $initialPreviewConfig = [];

        $userTempDir = $this->getModule()->getUserDirPath($attribute);

        if (is_dir($userTempDir)) {
            foreach (FileHelper::findFiles($userTempDir) as $file) {
                $filename = basename($file);
                $initialPreviewConfig[] = [
                    'caption' => $filename,
                    'showDrag' => false,
                    'indicatorNew' => false,
                    'showRemove' => true,
                    'size' => $file->size,
                    'url' => Url::to(['/' . FileModule::getModuleName() . '/file/delete-temp',
                        'filename' => $filename
                    ]),
                ];
            }
        }

        $files = $this->getFilesByAttributeName($attribute)->all();

        if (is_array($files)) {
            foreach ($files as $index => $file) {
                $initialPreviewConfig[] = [
                    'caption' => "$file->name.$file->type",
                    'showDrag' => false,
                    'indicatorNew' => false,
                    'showRemove' => true,
                    'size' => $file->size,
                    'url' => Url::toRoute(['/' . FileModule::getModuleName() . '/file/delete',
                        'id' => $file->id,
                        'item_id' => $this->owner->getAttribute('id'),
                        'model' => $this->getModule()->getClass($this->owner),
                        'attribute' => $attribute
                    ])
                ];
            }
        }

        return $initialPreviewConfig;
    }

    /**
     * @return int
     * @throws \Exception
     */
    public function getFileCount()
    {
        $count = File::find()
            ->where([
                'item_id' => $this->owner->getAttribute('id'),
                'model' => $this->getModule()->getClass($this->owner)
            ])
            ->count();
        return (int)$count;
    }

    /**
     * @return mixed
     */
    public function getStatsToolbar()
    {
        return StatsToolbarPanels::getDocumentsPanel($this->owner, $this->getFileCount());
    }

    private function saveFileFromDatabanks($attribute, $csrf, $datas)
    {
        $ok = true;

        foreach ($datas as $item) {
            if ($attribute == $item['attribute'] && !in_array($attribute, self::$savedDatabankAttributes)) {
                if ($item['type'] == AttachDatabankFile::className()) {
                    $ok = $this->saveFileFromDatabankFile($attribute, $item) && $ok;
                }
//                else if ($item['type'] == AttachGalleryImage::className()) {
//                    $ok = $this->saveFileFromGallery($attribute, $item) && $ok;
//                }
                self::$savedDatabankAttributes [] = $attribute;
            }
        }

        return true;
    }

    private function saveFileFromDatabankFile($attribute, $item)
    {
        $ok = false;
        $idsFile = $item['ids'];
        $databankFileAttribute = $item['attribute'];
        if ($attribute == $databankFileAttribute) {
            foreach ($idsFile as $idFile) {
                $file = AttachGenericFile::findOne($idFile);
                if ($file) {
                    $filePath = $file->getPath();
                    if (file_exists($filePath)) {
                        if ($this->getModule()->attachFile($filePath, $this->owner, $attribute, false, false, false, $file->name)) {
                            $ok = true;
                        }
                    }
                }
            }
        }
        return $ok;
    }


    private function saveFileFromGallery($attribute, $item)
    {
        $ok = false;
        $idFile = $item['id'];
        $galleryAttribute = $item['attribute'];

        if ($attribute == $galleryAttribute) {
            $image = AttachGenericImage::findOne($idFile);
            if ($image) {
                $filePath = $image->getPath();
                if (file_exists($filePath)) {
                    $this->deleteAttachments($this->owner, $attribute);
                    if ($a = $this->getModule()->attachFile($filePath, $this->owner, $attribute, false)) {
                        $ok = true;
                    }
                }
            }
        }
        return $ok;
    }


}
